spring.application.name=umusare
spring.profiles.active=local
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/umusare}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:God}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
app.admin.phone=${APP_ADMIN_PHONE:07815000000}
app.admin.password=${APP_ADMIN_PASSWORD:adminumusare12}
app.jwt.secret=${APP_JWT_SECRET:umusareSecretKeyChangeisgeneratedrandomlySomethingLongAndRandom12345678910111213141516.}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:cow.rmq2.cloudamqp.com}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5671}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:qvrpbpgr}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:0E26AWOQS3Cb4ssqmC2JuNK0HiN6Y4eO}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST:qvrpbpgr}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.listener.simple.missing-queues-fatal=false
app.oauth2.google.client-id=${APP_OAUTH2_GOOGLE_CLIENT_ID:placeholder}
