spring.application.name=umusare
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL}
spring.jpa.show-sql=false
app.admin.phone=${APP_ADMIN_PHONE}
app.admin.password=${APP_ADMIN_PASSWORD}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.listener.simple.missing-queues-fatal=false
